# .rubocop.yml

# rubocop config files for Ruby 2.7 / Rails 6+ project
# blog post: http://joanswork.com/rubocop-rails-getting-started/
# link broken, all I can find: https://github.com/jehughes

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

  Include:
    - '**/*.rb'

Layout/IndentationConsistency:
  EnforcedStyle: 'indented_internal_methods'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Metrics/BlockNesting:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/GlobalVars:
  Enabled: false
